version: "3.7"

services: 
  database_nest:
    image: postgres
    container_name: database_nest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest
    volumes:
      - pgdata:/data/postgres    
  app_nest:
    build: .
    container_name: app_nest
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_nest
    depends_on:
      - database_nest
    environment:
      - POSTGRES_HOST=database_nest
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=nest
      - PORT=3000
      - MODE=DEV
      - RUN_MIGRATIONS=true

volumes:
  pgdata:
    driver: local